// <auto-generated />
namespace _1811061325_LeTrongNhan_BigSchool.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FixFollowerId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixFollowerId));
        
        string IMigrationMetadata.Id
        {
            get { return "202107030508265_FixFollowerId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
